### PR TITLE
Creating SLSIntegrate function

### PR DESCRIPTION
**Pull request by trinhxuann**
This is the integrating function for SLS, in which the base Access tables are appropriately integrated into a long data format.

### CODE REVIEW

**Comment by sbashevkin** [comment]
Have you verified that the output of this function creates the exact same object currently stored as LTMRdata::SLS (with something like all.equal)?

**Comment by trinhxuann** [comment]
I have. I had sent out another email with a screenshot of the all.equal checks. I performed 2 checks, one was between the new function and the current SLS database in the package and the other was checking to see if when filePath was specified if it was the same output or not.

**Comment by sbashevkin** [comment]
Great! So how would this be used within the package itself? Would the SLS script in data-raw be reduced to just a call to this function?

**Comment by trinhxuann** [comment]
Running the script is noticeably slower than asking directly for the table. As this is your package, I leave the preference up to you. If you would like to simply use the current format in which the table is available on demand, I have no problem making the integrate function internal (:::). I had just wanted to use this script beyond the LTMR package for the EDI publishing process and did not want to reinvent the wheel and to give credit to this package.

My current thought on how this all works will be:

1. the survey crews will enter their data normally in Access as the season is going
2. the ES in charge will need to pull data from these base tables occasionally to produce reports and to QAQC, via functions in another github project that I have started for them
3. at the end of the quarter, the LTMR package becomes important, as the ES in charge will output the base tables to csv files, run this integration code to produce the integrated dataset, and upload all the necessary files to EDI.

Given that the survey crews may want to update to EDI at a different intervals than this package, I thought it would make sense to simply tap into this package. Due to that, the integrate function can be entirely internal if you wish to keep its current format.

Please let me know if you have any issues with that thought process!

**Comment by sbashevkin** [comment]
Hi Trinh,

Currently we have duplicate code in the data-raw/SLS.R file and in this function. I'm just asking how this function will replace that code, and how the internal SLS object will get updated using this function. I'm more interested in the integrated database than how CDFW staff will use these functions. I expect you will maintain it to keep it functional for CDFW staff, and I will keep the package working as an integrated dataset. As I've said before, I have no problem with this being an exported function, my question is just about how to avoid duplicated code and use this function to update the LTMRdata internal datasets. 

I think it would be most useful if you made all the changes you intend to make before we merge this PR. So that would be transitioning all the data-raw scripts into functions and converting all the R scripts in data-R to use the new functions. What do you think?

**Comment by trinhxuann** [comment]
I agree that these exported functions can replace the ones in the data raw folder. I can write the code in such a way that it outputs the rda to the data folder first, prioritizing the needs of yhe LTMR package by default. Is there an equivalent to the usethis function when doing this? Or should I simply use save image into the data folder?

I’ll work on the other datasets next before the next pull request.

Have a great weekend!

Best,
Trinh

Sent from my iPhone

On Dec 3, 2021, at 4:37 PM, Sam Bashevkin ***@***.***> wrote:

﻿

WARNING: This message is from an external source. Verify the sender and exercise caution when clicking links or opening attachments.


Hi Trinh,

Currently we have duplicate code in the data-raw/SLS.R file and in this function. I'm just asking how this function will replace that code, and how the internal SLS object will get updated using this function. I'm more interested in the integrated database than how CDFW staff will use these functions. I expect you will maintain it to keep it functional for CDFW staff, and I will keep the package working as an integrated dataset. As I've said before, I have no problem with this being an exported function, my question is just about how to avoid duplicated code and use this function to update the LTMRdata internal datasets.

I think it would be most useful if you made all the changes you intend to make before we merge this PR. So that would be transitioning all the data-raw scripts into functions and converting all the R scripts in data-R to use the new functions. What do you think?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsbashevkin%2FLTMRdata%2Fpull%2F18%23issuecomment-985929387&data=04%7C01%7Ctrinh.nguyen%40wildlife.ca.gov%7Cd89921779f914f438b1c08d9b6be3b6b%7C4b633c25efbf40069f1507442ba7aa0b%7C0%7C0%7C637741750427928049%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=3UDzJZhTMN75r%2FpYA1ITzHJ2t2wfDceOCa920CEWI1o%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALXYUCSJMWJFAOAXERXRRULUPFPEBANCNFSM5JK3B2TA&data=04%7C01%7Ctrinh.nguyen%40wildlife.ca.gov%7Cd89921779f914f438b1c08d9b6be3b6b%7C4b633c25efbf40069f1507442ba7aa0b%7C0%7C0%7C637741750427928049%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2BQgo%2BwrXtKv%2B8pX7us2N4Dp01oZ6RdtW1chJtWpGmP8%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ctrinh.nguyen%40wildlife.ca.gov%7Cd89921779f914f438b1c08d9b6be3b6b%7C4b633c25efbf40069f1507442ba7aa0b%7C0%7C0%7C637741750427938006%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=vboJX%2BKWBCXrbicKzvgfbwsB4Lo542Kdpqho3TELwW8%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ctrinh.nguyen%40wildlife.ca.gov%7Cd89921779f914f438b1c08d9b6be3b6b%7C4b633c25efbf40069f1507442ba7aa0b%7C0%7C0%7C637741750427938006%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=R6%2FxgUJXoEAI8FGWxi%2FbYxm1Vhwr1z8L3InmEl5rUig%3D&reserved=0>.

**Comment by sbashevkin** [comment]
I think you can keep the output of your function the same, but we would just call your function within the data-raw script before saving the data with usethis::use_data

**Pull request closed without merging**
