### PR TITLE
YBFMP code and raw and RDA data files

### PR DESCRIPTION
**Pull request by catarfish**
Hi Sam,
I had some issues with this dataset after doing some data cleaning for effort, and had to merge the sampleID back in with some of our raw files, so there are a few included. I put some notes up at the top of the code, not sure if this metadata can go in the package somewhere? It is regarding effort, as I only cleaned the effort for 2010 on, because there were just too many issues with the older data, and I would need more time to go through it. There is an additional effort file pulled from EDI that is monthly effort that can be used for the rest. Let me know if you notice any issues. Thanks!
Cat

### CODE REVIEW

**Comment by sbashevkin** [comment]
Hi @catarfish I'm not sure I understand what you mean by needing to merge SampleID back in with the raw data. Why were you not able to create the SampleID variable using just the EDI data?

It would be ideal to have all the data equally cleaned and included but if you are only able to clean 2010 to present for now, please exclude all data from prior years.

**Comment by catarfish** [comment]
Hi Sam,
I did end up using a newly created SampleID for the final ID, but I needed
the original sampleID to merge the effort with the sample table (effort
wasn't in the EDI publication). I tried using Datetime, and for some reason
it wouldn't work, plus I QA/QCed effort outside of your package and changed
some of the dates and times that were incorrectly recorded, so had to bring
some files in. Hopefully that's not a problem?

We have poor documentation of effort issues for earlier years, and
differences in how sampling was done/recorded, so not sure I will even
tackle some of the earlier years, but I can limit to 2010 for now and add
in if I have time to QC more.

**Comment by catarfish** [comment]
I pushed updates up to filter to 2010+, not sure if you can see them? A little confused about if I should be merging pull request or not.

**Comment by sbashevkin** [comment]
> I pushed updates up to filter to 2010+, not sure if you can see them? A little confused about if I should be merging pull request or not.

Yes I can see them, I'll merge it after I have time to check it over.

**Comment by sbashevkin** [comment]
@catarfish Are you planning to update this dataset on EDI soon? Can you make the edits to those files when you update them instead of including the separate CSVs here? I'm hesitant to include the edited CSVs in the package unless absolutely necessary since it makes it much more difficult to update the data in the future.

**Comment by catarfish** [comment]
Yes, I am, though am a few weeks out at least. I also found some issues
with the zooplankton data (just a few days with duplicates that I need to
track down the issues and fix) when I tried converting to wide. Was going
to update that publication, probably just for those edits for now. I'll
update everything then once those are published. We aren't quite at the
point of analyzing those datasets yet, so I'll prioritize those updates.

**Pull request closed without merging**
